backend:
  name: git-gateway
  repo: wwl3leathers/wwl3leathers.github.io
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/5034d694-24bf-47dd-9147-53afd4d322ca/pkce
  auth_token_endpoint: /sites/5034d694-24bf-47dd-9147-53afd4d322ca/token
  gateway_url: https://gateway.decapbridge.com

media_library:
  name: simple

media_folder: assets/uploads
public_folder: /assets/uploads

collections:
  - name: pages
    label: Pages
    folder: content/pages
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
